version: '3'

volumes:
  db_vol:
    driver: local

services:
  db:
    image: mysql/mysql-server:8.0
    container_name: parser-db
    restart: always
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_520_ci
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: parser_db
    ports:
      - '33080:3306'
    volumes:
      - db_vol:/var/lib/mysql

  redis:
    container_name: parser-redis
    image: redis:alpine
    command: redis-server --port 6379
    ports:
      - '6379:6379'
    labels:
      - 'name=redis'
      - 'mode=standalone'
